### ISSUE TITLE
书P60表3-4不可重复读有误?

### ISSUE THREAD

**Issue by miniyk2012** [tangwz/DistSysDeepDive#2]
不可重复读指的是B事务在执行过程中, 由于另一个事务A对某条数据的提交, 导致B在A提交前和A提交后的2次读到的数据不一致. 我觉得表3-4应该长这样:

假设x初始值为0
|事务A        |事务B      |
|----------|----------|
|                 |Read(x)    |
|x=1           |                 |
|commit    |                 |
|                 |Read(x)   |
|                 |commit    |

则事务B前后2次分别读到0和1

**Comment by miniyk2012** [comment]
同理, 表3-5的幻读也有误.
事务A的commit应该和A的insert在一起.

**Comment by tangwz** [comment]
对的。
