### ISSUE TITLE
书p60页倒数第六行：从节点负载过高会影响写请求完成

### ISSUE THREAD

**Issue by tychozzz** [tangwz/DistSysDeepDive#3]
应该更改为主节点负载过高吧？单主复制模式下，主节点负责写请求。

**Comment by tangwz** [comment]
> 应该更改为主节点负载过高吧？单主复制模式下，主节点负责写请求。

应该说都会。这里主要突出的点应该是，主节点正常的情况下，为了高可用添加了从节点，但是从节点如果接收数据慢，反而影响了整个写请求。

这里我会考虑换一种表达方式。
