### ISSUE TITLE
226页符号有误（22年6月第二次印刷版）

### ISSUE THREAD

**Issue by ghost** [tangwz/DistSysDeepDive#4]
倒数第二行和倒数第三行
“分布输出系统事件的全序关系用=>来表示，a≥b意味着事件a在全序关系上发生于事件b之前。定义a≥b满足”
应为
“分布输出系统事件的全序关系用=>来表示，**a=>b**意味着事件a在全序关系上发生于事件b之前。定义**a=>b**满足”

**Comment by tangwz** [comment]
嗯，这个应该是编辑排版失误了，我反馈下，感谢。
